### ISSUE TITLE
Expose `nargo contract` in TS

### ISSUE THREAD

**Issue by signorecello** [noir-lang/noir_wasm#5]
### Problem

For deploying programatically (eg. using Hardhat), it would be very useful to have the equivalent `nargo contract` in `noir_wasm`

### Proposed solution

A solution would be to create a function that calls this function, pretty much like it does for `nargo compile` and `import { compile } from "@noir-lang/noir_wasm"`

The suggested use would be (pseudocode):

```
import { generateContract } from "@noir-lang/noir_wasm"

const { interface, bytecode } = generateContract("../main.nr")
const contract = new ethers.ContractFactory(interface, bytecode)

etc
```

### Alternatives considered

An alternative is to call `execSync` in node, that basically calls `nargo contract` in a bash shell. This works but requires nargo to be installed on the machine.

Currently the most concise way to do this with one npm/yarn command is to have three steps, like:

```
{
...
 "deploy:local": "hardhat run scripts/genContract.ts && hardhat compile && hardhat run --network localhost scripts/deploy.ts",
}
```

This doesn't seem ideal

**Comment by kobyhallx** [comment]
Closing because option is available to achieve this here:
https://github.com/noir-lang/noir/blob/master/crates/wasm/src/compile.rs#L24.

This will change soon with CrateType setting so this interface will likely follow.

**Comment by TomAFrench** [comment]
This is for exposing `nargo codegen-verifier` through TS not compilation of noir contracts. This isn't a concern for `noir_wasm` though as it's a responsibility of bb.js.
